name: Test Action "Github Actions Best Practices"

on:
  push:
  workflow_dispatch:

steps:
  - name: Checkout
    id: checkout
    uses: actions/checkout@v4

  - name: Test Action "Github Actions Best Practices"
    id: test-action
    uses: ./
